name: CI

on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install and test backend
        run: |
          cd fft_backend
          npm ci
          npm test
        env:
          CI: true
      - name: npm install and test frontend
        run: |
          cd fft_frontend
          npm ci
          npm test
        env:
          CI: true
      - name: Create production build
        run: |
          pwd
          cd fft_backend
          npm run build:ui
      - name: Add remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy to Heroku
        run: git push --force heroku `git subtree split --prefix fft_backend HEAD`:master

           
