name: CI

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install and test backend
        run: |
          cd fft_backend
          npm ci
          npm test
        env:
          CI: true
      - name: npm install and test frontend
        run: |
          cd fft_frontend
          npm ci
          npm test
        env:
          CI: true
