name: CI/CD

on: 
  push:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install and test backend
        run: |
          cd fft_backend
          npm ci
          npm test
        env:
          CI: true
      - name: npm install and test frontend
        run: |
          cd fft_frontend
          npm ci
          npm test
        env:
          CI: true
   
  build:
    name: Create production build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: Create production build
        run: |
          pwd
          cd fft_backend
          npm run build:ui
  
  deploy:
    name: Deploy to heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "partanen.joonas@gmail.com"
          appdir: "fft_backend"        
