name: CI/CD

on:
  push:
    branches: [master]

jobs:
  ci-cd-pipeline:
    name: CI/CD pipeline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Backend / npm install
        run: |
          npm ci
      - name: Backend / run tests
        run: npm test
        env:
          CI: true
      - name: Frontend / npm install
        working-directory: ./client
        run: |
          npm ci
      - name: Frontend / run tests
        working-directory: ./client
        run: npm test
        env:
          CI: true
      - name: Build frontend
        working-directory: ./client
        run: |
          npm run build --prod
