name: CI/CD
concurrency: production

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  ci-cd-pipeline:
    name: CI/CD pipeline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            client/package-lock.json

      - name: Backend / npm install
        run: |
          npm ci
      - name: Backend / run tests
        run: npm test
        env:
          CI: true
      - name: Frontend / npm install
        working-directory: ./client
        run: |
          npm ci
      - name: Frontend / build
        working-directory: ./client
        run: |
          npm run build --prod
      - name: Frontend / run tests
        working-directory: ./client
        run: npm test
        env:
          CI: true
      - uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "finnish-foreign-trade"
          heroku_email: ${{secrets.HEROKU_USERNAME}}
          branch: master
          healthcheck: "https://finnish-foreign-trade.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        if: ${{ github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '#tag') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Generate dummy id
        run: echo "123" > id.txt
      - name: Test artifact upload
        uses: actions/upload-artifact@v2
        with:
          name: deployment-id
          path: id.txt

  complete-deployment:
    name: Complete deployment
    runs-on: ubuntu-18.04
    needs: ci-cd-pipeline
    environment:
      name: production
      url: https://finnish-foreign-trade.herokuapp.com/
    steps:
      - uses: actions/checkout@v2
      - name: Print message
        run: echo "Finished deployment"

      - name: Test artifact download
        uses: actions/download-artifact@v2
        with:
          name: deployment-id
      - name: Print the dummy deployment id
        run: |
          value=`cat id.txt`
          echo The deployment id is $value
